const medicalPhrases = [
  // --------------------------------------------------
  // Application and dictation context
  // --------------------------------------------------
  'AI speech-to-text test',
  'speech-to-text',
  'speech to text',
  'speech-to-text engine',
  'voice recognition',
  'voice input',
  'voice dictation',
  'medical dictation',
  'medical transcription',
  'medical transcriptions',
  'clinical transcription',
  'doctor dictation',
  'patient intake',
  'patient history',
  'clinical history',
  'chief complaint',
  'presenting complaint',
  'history taking',
  'symptom capture',
  'triage note',
  'OPD note',
  'IPD note',
  'emergency note',
  'discharge summary',
  'prescription note',
  'follow up note',
  'testing this',
  'testing this in several ways',

  // --------------------------------------------------
  // Hospital workflow / Indian hospital terms
  // --------------------------------------------------
  'OPD',
  'outpatient department',
  'IPD',
  'inpatient department',
  'emergency',
  'casualty',
  'ER',
  'ICU',
  'CCU',
  'NICU',
  'PICU',
  'HDU',
  'ward',
  'general ward',
  'private ward',
  'semi private ward',
  'cabin',
  'bed number',
  'admission',
  'discharge',
  'referral',
  'referred by doctor',
  'follow up',
  'review after one week',
  'registration counter',
  'billing counter',
  'pharmacy',
  'medicine counter',
  'sample collection',
  'pathology',
  'radiology',
  'diagnostic centre',
  'lab report',
  'test report',
  'health card',
  'MRD',
  'medical record department',
  'UHID',
  'patient ID',
  'registration number',
  'queue number',
  'token number',
  'appointment',
  'walk in patient',
  'old patient',
  'new patient',
  'attendant',
  'patient party',
  'relative',
  'insurance',
  'TPA',
  'cashless',
  'Ayushman card',
  'Swasthya Sathi',
  'ESI',
  'CGHS',
  'health scheme',
  'medical certificate',
  'fitness certificate',
  'death certificate',
  'birth certificate',

  // --------------------------------------------------
  // Departments / specialties
  // --------------------------------------------------
  'general medicine',
  'general physician',
  'family physician',
  'pediatrician',
  'paediatrics',
  'child specialist',
  'gynecologist',
  'gynaecologist',
  'obstetrician',
  'orthopedic',
  'orthopaedic',
  'bone doctor',
  'ENT',
  'ear nose throat',
  'ophthalmology',
  'eye specialist',
  'dermatology',
  'skin specialist',
  'neurology',
  'neurologist',
  'neurosurgery',
  'cardiology',
  'cardiologist',
  'pulmonology',
  'chest physician',
  'gastroenterology',
  'gastroenterologist',
  'nephrology',
  'urology',
  'endocrinology',
  'diabetologist',
  'psychiatry',
  'psychologist',
  'oncology',
  'cancer specialist',
  'dentist',
  'dental',
  'physiotherapy',
  'dietician',
  'nutritionist',

  // --------------------------------------------------
  // General symptoms
  // --------------------------------------------------
  'abdominal pain',
  'acid reflux',
  'acidity',
  'back pain',
  'bleeding',
  'blurred vision',
  'body ache',
  'breathlessness',
  'burning sensation',
  'chest pain',
  'chills',
  'constipation',
  'cough',
  'dizziness',
  'dry cough',
  'ear pain',
  'fatigue',
  'fever',
  'high fever',
  'low grade fever',
  'headache',
  'heartburn',
  'joint pain',
  'loss of appetite',
  'loss of smell',
  'loss of taste',
  'nausea',
  'palpitations',
  'rash',
  'runny nose',
  'shortness of breath',
  'sore throat',
  'stomach pain',
  'swelling',
  'vomiting',
  'weakness',
  'wheezing',
  'weight loss',
  'weight gain',
  'night sweats',
  'sweating',
  'excessive sweating',
  'tiredness',
  'lethargy',
  'body weakness',
  'general weakness',
  'loss of consciousness',
  'fainting',
  'blackout',
  'confusion',
  'irritability',
  'restlessness',
  'sleep problem',
  'insomnia',
  'poor sleep',
  'loss of energy',

  // --------------------------------------------------
  // Pain descriptions
  // --------------------------------------------------
  'mild pain',
  'moderate pain',
  'severe pain',
  'very severe pain',
  'acute pain',
  'chronic pain',
  'sharp pain',
  'dull pain',
  'burning pain',
  'stabbing pain',
  'cramping pain',
  'throbbing pain',
  'radiating pain',
  'shooting pain',
  'electric shock like pain',
  'pins and needles',
  'tingling sensation',
  'numbness',
  'pressure sensation',
  'heaviness',
  'tightness',
  'pain increases on movement',
  'pain decreases on rest',
  'pain after food',
  'pain before food',
  'pain during urination',
  'pain while passing stool',
  'pain while walking',
  'pain at night',
  'pain since morning',
  'pain since yesterday',
  'pain for two days',
  'pain for one week',
  'pain on right side',
  'pain on left side',

  // --------------------------------------------------
  // Anatomy and complaint locations
  // --------------------------------------------------
  'abdomen',
  'ankle',
  'arm',
  'back',
  'chest',
  'ear',
  'eye',
  'foot',
  'hand',
  'head',
  'knee',
  'leg',
  'lower abdomen',
  'lower back',
  'neck',
  'shoulder',
  'throat',
  'upper abdomen',
  'forehead',
  'temple',
  'scalp',
  'face',
  'jaw',
  'tooth',
  'gum',
  'tongue',
  'mouth',
  'lip',
  'nose',
  'sinus',
  'collar bone',
  'rib',
  'left chest',
  'right chest',
  'central chest',
  'upper back',
  'mid back',
  'spine',
  'hip',
  'groin',
  'pelvis',
  'waist',
  'wrist',
  'elbow',
  'finger',
  'thumb',
  'toe',
  'heel',
  'sole',
  'calf',
  'thigh',
  'buttock',
  'navel',
  'umbilicus',
  'right upper abdomen',
  'left upper abdomen',
  'right lower abdomen',
  'left lower abdomen',
  'epigastric region',
  'flank',
  'right flank',
  'left flank',
  'genital area',
  'urinary bladder area',
  'anal region',

  // --------------------------------------------------
  // Fever / infection / viral symptoms
  // --------------------------------------------------
  'fever with chills',
  'fever with shivering',
  'fever with cough',
  'fever with body ache',
  'fever with headache',
  'fever with rash',
  'fever with vomiting',
  'fever with diarrhea',
  'continuous fever',
  'intermittent fever',
  'evening fever',
  'night fever',
  'viral fever',
  'seasonal fever',
  'flu like symptoms',
  'cold and cough',
  'common cold',
  'influenza',
  'COVID',
  'COVID positive',
  'COVID negative',
  'dengue',
  'malaria',
  'typhoid',
  'chikungunya',
  'jaundice',
  'hepatitis',
  'infection',
  'bacterial infection',
  'viral infection',
  'throat infection',
  'chest infection',
  'urine infection',
  'skin infection',
  'wound infection',

  // --------------------------------------------------
  // Respiratory / ENT symptoms
  // --------------------------------------------------
  'cough with phlegm',
  'productive cough',
  'dry cough',
  'wet cough',
  'blood in sputum',
  'yellow sputum',
  'green sputum',
  'white sputum',
  'chest congestion',
  'nasal congestion',
  'blocked nose',
  'stuffy nose',
  'running nose',
  'sneezing',
  'sinus pain',
  'sinus pressure',
  'post nasal drip',
  'hoarseness of voice',
  'voice change',
  'loss of voice',
  'sore throat',
  'throat pain',
  'difficulty swallowing',
  'pain while swallowing',
  'tonsil pain',
  'ear discharge',
  'ear blockage',
  'ear ringing',
  'tinnitus',
  'hearing loss',
  'vertigo',
  'breathing difficulty',
  'shortness of breath',
  'wheezing',
  'asthma attack',
  'bronchitis',
  'pneumonia',
  'COPD',
  'allergic rhinitis',
  'sinusitis',
  'tonsillitis',

  // --------------------------------------------------
  // Gastrointestinal symptoms
  // --------------------------------------------------
  'gas',
  'gas problem',
  'acidity problem',
  'indigestion',
  'bloating',
  'abdominal bloating',
  'belching',
  'burping',
  'heartburn',
  'acid reflux',
  'GERD',
  'gastritis',
  'loose motion',
  'diarrhea',
  'watery stool',
  'blood in stool',
  'black stool',
  'mucus in stool',
  'constipation',
  'hard stool',
  'piles',
  'hemorrhoids',
  'fissure',
  'fistula',
  'anal pain',
  'rectal bleeding',
  'vomiting',
  'nausea',
  'food poisoning',
  'loss of appetite',
  'early satiety',
  'difficulty digesting food',
  'stomach upset',
  'stomach cramps',
  'abdominal cramps',
  'ulcer',
  'peptic ulcer',
  'liver problem',
  'fatty liver',
  'gall bladder stone',
  'gallstone',
  'appendix pain',
  'appendicitis',
  'pancreatitis',

  // --------------------------------------------------
  // Cardiac / BP symptoms
  // --------------------------------------------------
  'blood pressure',
  'high blood pressure',
  'low blood pressure',
  'hypertension',
  'hypotension',
  'chest heaviness',
  'chest tightness',
  'left sided chest pain',
  'pain radiating to left arm',
  'pain radiating to jaw',
  'palpitations',
  'fast heartbeat',
  'irregular heartbeat',
  'slow heartbeat',
  'breathlessness on exertion',
  'swelling of feet',
  'ankle swelling',
  'heart disease',
  'heart attack',
  'myocardial infarction',
  'angina',
  'ECG changes',
  'cardiac arrest',
  'stroke',
  'TIA',
  'high cholesterol',
  'triglycerides',

  // --------------------------------------------------
  // Diabetes / endocrine
  // --------------------------------------------------
  'diabetes',
  'blood sugar',
  'high sugar',
  'low sugar',
  'fasting sugar',
  'post prandial sugar',
  'PP sugar',
  'HbA1c',
  'insulin',
  'thyroid',
  'hypothyroidism',
  'hyperthyroidism',
  'TSH',
  'weight gain',
  'weight loss',
  'excessive thirst',
  'excessive urination',
  'frequent urination',
  'increased appetite',
  'sugar patient',
  'diabetic patient',
  'diabetic foot',
  'hypoglycemia',
  'hyperglycemia',

  // --------------------------------------------------
  // Urinary / kidney symptoms
  // --------------------------------------------------
  'urinary tract infection',
  'UTI',
  'urine infection',
  'burning urination',
  'burning while passing urine',
  'frequent urination',
  'urgent urination',
  'difficulty passing urine',
  'low urine output',
  'blood in urine',
  'dark urine',
  'cloudy urine',
  'foamy urine',
  'kidney stone',
  'renal stone',
  'flank pain',
  'prostate problem',
  'urinary retention',
  'bed wetting',
  'incontinence',
  'creatinine',
  'urea',
  'kidney function test',
  'KFT',
  'dialysis',

  // --------------------------------------------------
  // Neurology / mental health
  // --------------------------------------------------
  'headache',
  'migraine',
  'vertigo',
  'dizziness',
  'seizure',
  'fits',
  'convulsion',
  'epilepsy',
  'stroke',
  'paralysis',
  'facial deviation',
  'slurred speech',
  'weakness of one side',
  'numbness of one side',
  'memory loss',
  'confusion',
  'tremor',
  'shaking hands',
  'Parkinson',
  'anxiety',
  'panic attack',
  'depression',
  'stress',
  'fear',
  'sleep disturbance',
  'suicidal thoughts',
  'irritability',
  'mood swings',
  'hallucination',

  // --------------------------------------------------
  // Skin / allergy
  // --------------------------------------------------
  'allergy',
  'skin allergy',
  'rash',
  'itching',
  'hives',
  'urticaria',
  'eczema',
  'psoriasis',
  'fungal infection',
  'ringworm',
  'scabies',
  'boil',
  'abscess',
  'pimple',
  'acne',
  'dark spots',
  'white patches',
  'skin peeling',
  'skin redness',
  'swollen face',
  'swollen lips',
  'drug allergy',
  'food allergy',
  'insect bite',
  'mosquito bite',
  'dog bite',
  'cat bite',
  'snake bite',
  'burn injury',
  'wound',
  'cut injury',
  'ulcer',
  'diabetic ulcer',

  // --------------------------------------------------
  // Bone / joint / injury
  // --------------------------------------------------
  'joint pain',
  'knee pain',
  'shoulder pain',
  'neck pain',
  'back pain',
  'lower back pain',
  'sciatica',
  'slip disc',
  'cervical spondylosis',
  'lumbar spondylosis',
  'arthritis',
  'rheumatoid arthritis',
  'osteoarthritis',
  'gout',
  'uric acid',
  'muscle pain',
  'muscle spasm',
  'sprain',
  'strain',
  'fracture',
  'dislocation',
  'swelling after injury',
  'fall injury',
  'road traffic accident',
  'RTA',
  'sports injury',
  'plaster',
  'cast',
  'X-ray',
  'MRI spine',
  'physiotherapy',

  // --------------------------------------------------
  // Women’s health / pregnancy
  // --------------------------------------------------
  'period problem',
  'irregular periods',
  'heavy bleeding',
  'less bleeding',
  'painful periods',
  'menstrual cramps',
  'missed period',
  'white discharge',
  'vaginal discharge',
  'vaginal itching',
  'burning in private part',
  'pregnancy',
  'pregnancy test',
  'urine pregnancy test',
  'UPT',
  'antenatal checkup',
  'ANC',
  'last menstrual period',
  'LMP',
  'expected date of delivery',
  'EDD',
  'labour pain',
  'normal delivery',
  'cesarean section',
  'C section',
  'breast pain',
  'breast lump',
  'breast feeding',
  'lactation',
  'PCOS',
  'PCOD',
  'fibroid',
  'endometriosis',
  'menopause',

  // --------------------------------------------------
  // Child health
  // --------------------------------------------------
  'child fever',
  'baby fever',
  'feeding problem',
  'poor feeding',
  'vomiting in child',
  'loose motion in child',
  'cough in child',
  'wheezing in child',
  'convulsion in child',
  'vaccination',
  'immunization',
  'BCG vaccine',
  'DPT vaccine',
  'polio drops',
  'measles vaccine',
  'MMR vaccine',
  'growth chart',
  'weight for age',
  'newborn',
  'neonate',
  'infant',
  'toddler',
  'jaundice in newborn',
  'dehydration in child',

  // --------------------------------------------------
  // Eye / dental
  // --------------------------------------------------
  'eye pain',
  'red eye',
  'watering of eyes',
  'itchy eyes',
  'blurred vision',
  'double vision',
  'loss of vision',
  'cataract',
  'glaucoma',
  'conjunctivitis',
  'spectacles',
  'eye power',
  'tooth pain',
  'dental pain',
  'gum bleeding',
  'mouth ulcer',
  'bad breath',
  'loose tooth',
  'root canal',
  'tooth extraction',
  'dental cavity',

  // --------------------------------------------------
  // Common diagnoses / clinical terms
  // --------------------------------------------------
  'allergy',
  'anemia',
  'anaemia',
  'anxiety',
  'asthma',
  'bronchitis',
  'COVID',
  'dehydration',
  'depression',
  'diabetes',
  'diarrhea',
  'gastritis',
  'hypertension',
  'hypothyroidism',
  'infection',
  'influenza',
  'migraine',
  'pneumonia',
  'sinusitis',
  'urinary tract infection',
  'tuberculosis',
  'TB',
  'dengue fever',
  'malaria',
  'typhoid fever',
  'chickenpox',
  'measles',
  'mumps',
  'herpes',
  'herpes zoster',
  'shingles',
  'post herpetic neuralgia',
  'kidney disease',
  'liver disease',
  'heart disease',
  'COPD',
  'epilepsy',
  'stroke',
  'paralysis',
  'cancer',
  'tumor',
  'benign tumor',
  'malignant tumor',

  // --------------------------------------------------
  // Investigations / tests
  // --------------------------------------------------
  'CBC',
  'complete blood count',
  'hemoglobin',
  'haemoglobin',
  'platelet count',
  'TLC',
  'DLC',
  'ESR',
  'CRP',
  'LFT',
  'liver function test',
  'KFT',
  'kidney function test',
  'RFT',
  'renal function test',
  'blood sugar fasting',
  'blood sugar PP',
  'random blood sugar',
  'HbA1c',
  'lipid profile',
  'thyroid profile',
  'TSH',
  'T3',
  'T4',
  'urine routine',
  'urine culture',
  'stool routine',
  'stool occult blood',
  'sputum test',
  'sputum AFB',
  'malaria parasite',
  'dengue NS1',
  'dengue IgM',
  'typhoid test',
  'Widal test',
  'blood culture',
  'ECG',
  'echo cardiography',
  '2D echo',
  'TMT',
  'chest X-ray',
  'X-ray',
  'ultrasound',
  'USG abdomen',
  'CT scan',
  'MRI',
  'MRI brain',
  'MRI spine',
  'PET CT',
  'biopsy',
  'FNAC',
  'endoscopy',
  'colonoscopy',
  'spirometry',
  'oxygen saturation',
  'SpO2',
  'pulse rate',
  'temperature',
  'respiratory rate',
  'blood pressure reading',

  // --------------------------------------------------
  // Vitals and measurement phrases
  // --------------------------------------------------
  'BP is high',
  'BP is low',
  'sugar is high',
  'sugar is low',
  'pulse is high',
  'oxygen is low',
  'oxygen saturation is low',
  'temperature is high',
  'fever is 102',
  'BP 120 by 80',
  'BP 140 by 90',
  'fasting sugar 120',
  'PP sugar 180',
  'SpO2 95 percent',
  'weight 70 kg',
  'height 5 feet 6 inches',
  'BMI',
  'body mass index',

  // --------------------------------------------------
  // Medicine forms and dosing words
  // --------------------------------------------------
  'medicine',
  'medication',
  'prescription',
  'tablet',
  'capsule',
  'syrup',
  'injection',
  'ointment',
  'cream',
  'gel',
  'lotion',
  'drops',
  'eye drops',
  'ear drops',
  'nasal spray',
  'inhaler',
  'nebulizer',
  'nebulisation',
  'oral solution',
  'ORS',
  'powder',
  'sachet',
  'suppository',
  'patch',
  'one tablet daily',
  'twice daily',
  'three times daily',
  'after food',
  'before food',
  'empty stomach',
  'at bedtime',
  'morning dose',
  'night dose',
  'SOS',
  'as required',
  'continue medicine',
  'stop medicine',
  'missed dose',
  'side effect',
  'drug allergy',

  // --------------------------------------------------
  // Generic medicine names
  // --------------------------------------------------
  'acetaminophen',
  'paracetamol',
  'ibuprofen',
  'aspirin',
  'diclofenac',
  'aceclofenac',
  'naproxen',
  'etoricoxib',
  'tramadol',
  'pregabalin',
  'gabapentin',
  'amitriptyline',
  'nortriptyline',
  'duloxetine',
  'lidocaine',
  'lignocaine',
  'antibiotic',
  'amoxicillin',
  'amoxicillin clavulanate',
  'azithromycin',
  'cefexime',
  'cefixime',
  'cefuroxime',
  'ceftriaxone',
  'cefpodoxime',
  'ciprofloxacin',
  'ofloxacin',
  'levofloxacin',
  'doxycycline',
  'metronidazole',
  'tinidazole',
  'ornidazole',
  'albendazole',
  'ivermectin',
  'acyclovir',
  'valacyclovir',
  'oseltamivir',
  'fluconazole',
  'itraconazole',
  'pantoprazole',
  'omeprazole',
  'rabeprazole',
  'esomeprazole',
  'domperidone',
  'ondansetron',
  'metoclopramide',
  'sucralfate',
  'antacid',
  'simethicone',
  'lactulose',
  'bisacodyl',
  'dicyclomine',
  'mebeverine',
  'cetirizine',
  'levocetirizine',
  'fexofenadine',
  'montelukast',
  'chlorpheniramine',
  'phenylephrine',
  'ambroxol',
  'guaifenesin',
  'dextromethorphan',
  'salbutamol',
  'levosalbutamol',
  'budesonide',
  'formoterol',
  'tiotropium',
  'amlodipine',
  'telmisartan',
  'losartan',
  'olmesartan',
  'atenolol',
  'metoprolol',
  'bisoprolol',
  'hydrochlorothiazide',
  'chlorthalidone',
  'furosemide',
  'torsemide',
  'spironolactone',
  'atorvastatin',
  'rosuvastatin',
  'clopidogrel',
  'warfarin',
  'rivaroxaban',
  'apixaban',
  'metformin',
  'glimepiride',
  'gliclazide',
  'sitagliptin',
  'vildagliptin',
  'dapagliflozin',
  'empagliflozin',
  'insulin',
  'thyroxine',
  'levothyroxine',
  'carbimazole',
  'prednisolone',
  'dexamethasone',
  'hydrocortisone',
  'calcium',
  'vitamin D',
  'vitamin B12',
  'folic acid',
  'iron supplement',
  'zinc',
  'multivitamin',
  'ORS',
  'oral rehydration solution',

  // --------------------------------------------------
  // Common Indian brand names / commonly heard brands
  // Verify locally before using for clinical logic
  // --------------------------------------------------
  'Crocin',
  'Calpol',
  'Dolo',
  'Dolo 650',
  'Cipmol',
  'Combiflam',
  'Brufen',
  'Ibugesic',
  'Voveran',
  'Hifenac',
  'Zerodol',
  'Zerodol P',
  'Signoflam',
  'Nucoxia',
  'Ultracet',
  'Shelcal',
  'Shelcal 500',
  'Becosules',
  'Neurobion',
  'Nuhenz',
  'Supradyn',
  'Zincovit',
  'A to Z',
  'Limcee',
  'Uprise D3',
  'Calcirol',
  'Orofer',
  'Dexorange',

  // Antibiotic brands heard in India
  'Augmentin',
  'Clavam',
  'Moxikind CV',
  'Azithral',
  'Azee',
  'Zithromax',
  'Cefix',
  'Taxim O',
  'Mahacef',
  'Cepodem',
  'Ceftum',
  'Cifran',
  'Oflox',
  'Levoflox',
  'Doxy',
  'Doxicip',
  'Flagyl',
  'Metrogyl',
  'O2 tablet',
  'Norflox TZ',
  'Zifi',
  'Zifi CV',

  // Acidity / stomach brands
  'Pan D',
  'Pan 40',
  'Pantocid',
  'Pantocid DSR',
  'Panto D',
  'Rantac',
  'Razo',
  'Razo D',
  'Omez',
  'Omez D',
  'Nexpro',
  'Sompraz',
  'Gelusil',
  'Digene',
  'Eno',
  'Mucaine gel',
  'Cyclopam',
  'Spasmo Proxyvon',
  'Econorm',
  'Enterogermina',
  'Vizylac',
  'Lactobacillus',
  'Duphalac',

  // Cough cold allergy brands
  'Cetzine',
  'Okacet',
  'Levocet',
  'Allegra',
  'Montair',
  'Montek LC',
  'Telekast L',
  'Sinarest',
  'D Cold Total',
  'Cheston Cold',
  'Alex cough syrup',
  'Ascoril',
  'Benadryl',
  'Corex',
  'Grilinctus',
  'T Minic',
  'Nasoclear',
  'Otrivin',
  'Duolin',
  'Budecort',
  'Asthalin',
  'Foracort',
  'Seroflo',
  'Deriphyllin',

  // BP / heart / cholesterol brands
  'Telma',
  'Telma H',
  'Telma AM',
  'Tazloc',
  'Tazloc H',
  'Amlong',
  'Amlopres',
  'Losar',
  'Olmezest',
  'Concor',
  'Metolar',
  'Betaloc',
  'Ecosprin',
  'Clopilet',
  'Deplatt',
  'Atorva',
  'Storvas',
  'Rozavel',
  'Rosuvas',
  'Lasix',
  'Dytor',
  'Aldactone',

  // Diabetes / thyroid brands
  'Glycomet',
  'Glycomet GP',
  'Glyciphage',
  'Glucored',
  'Amaryl',
  'Diamicron',
  'Januvia',
  'Galvus',
  'Istamet',
  'Janumet',
  'Forxiga',
  'Jardiance',
  'Lantus',
  'Mixtard',
  'Huminsulin',
  'Thyronorm',
  'Eltroxin',
  'Neo Mercazole',

  // Neuro / pain / shingles-related brands
  'Pregaba',
  'Pregalin',
  'Lyrica',
  'Gabapin',
  'Gabapin NT',
  'Nervijen',
  'Nurokind',
  'Nurokind LC',
  'Amitone',
  'Tryptomer',
  'Duzela',
  'Valcivir',
  'Acivir',
  'Zovirax',
  'Lox 2 percent',
  'Lignocaine gel',
  'Lidocaine patch',

  // Skin brands
  'Candid',
  'Candid B',
  'Surfaz',
  'Betnovate',
  'Quadriderm',
  'Soframycin',
  'T Bact',
  'Mupirocin',
  'Fucidin',
  'Caladryl',
  'Permite',
  'Scaboma',
  'Ketoconazole',
  'KZ lotion',
  'Lulifin',
  'Lulican',
  'Terbinaforce',

  // --------------------------------------------------
  // Patient-history phrases
  // --------------------------------------------------
  'blood pressure',
  'blood sugar',
  'family history',
  'medical history',
  'past history',
  'surgical history',
  'allergy history',
  'drug allergy history',
  'current medication',
  'regular medicine',
  'old prescription',
  'previous report',
  'symptoms started',
  'started today',
  'started yesterday',
  'started last night',
  'since yesterday',
  'since morning',
  'since last night',
  'for two days',
  'for three days',
  'for five days',
  'for one week',
  'for two weeks',
  'for one month',
  'for six months',
  'for one year',
  'on and off',
  'comes and goes',
  'getting worse',
  'getting better',
  'not improving',
  'recurrent problem',
  'same problem before',
  'first time problem',
  'no fever',
  'no cough',
  'no vomiting',
  'no loose motion',
  'no chest pain',
  'no breathlessness',
  'no allergy',
  'no diabetes',
  'no blood pressure',
  'severe pain',
  'mild pain',
  'moderate pain',

  // --------------------------------------------------
  // Roman Hindi / Hinglish patient phrases
  // --------------------------------------------------
  'bukhar',
  'tez bukhar',
  'halka bukhar',
  'khansi',
  'sukhi khansi',
  'balgam wali khansi',
  'saans phoolna',
  'saans lene mein dikkat',
  'gala dard',
  'gale mein jalan',
  'naak band',
  'naak behna',
  'chakkar',
  'sir dard',
  'pet dard',
  'pet mein gas',
  'gas ho raha hai',
  'acidity ho raha hai',
  'jalan ho raha hai',
  'ulti',
  'ulti jaisa lag raha hai',
  'loose motion',
  'dast',
  'kabz',
  'bhookh nahi lag raha',
  'kamjori',
  'bahut kamjori',
  'thakan',
  'body pain',
  'haath pair dard',
  'jodon ka dard',
  'kamar dard',
  'seene mein dard',
  'seene mein jalan',
  'dhadkan tez',
  'BP high',
  'sugar high',
  'peshab mein jalan',
  'bar bar peshab',
  'peshab ruk ruk ke aana',
  'peshab mein khoon',
  'pair sujan',
  'chehre par sujan',
  'khujli',
  'daane',
  'chamri mein daag',
  'ghav',
  'kutta kaata',
  'saap kaata',
  'current jaisa dard',
  'bijli jaisa dard',
  'sui chubhne jaisa',
  'sunpan',
  'jhanjhanahat',
  'dard badh raha hai',
  'dard kam ho raha hai',
  'khana khane ke baad dard',
  'khali pet dard',

  // --------------------------------------------------
  // Roman Bengali / Bangla-English patient phrases
  // --------------------------------------------------
  'jor',
  'bukhar hoyeche',
  'jwar hoyeche',
  'kashi',
  'sukno kashi',
  'kof kashi',
  'shash kosto',
  'shash nite osubidha',
  'gola betha',
  'gola jwala',
  'nak bondho',
  'nak diye jol porche',
  'matha betha',
  'matha ghora',
  'chokh jhapsha',
  'kan betha',
  'pet betha',
  'pet e gas',
  'gas hoyeche',
  'ombol',
  'acidity',
  'buk jwala',
  'bomi',
  'bomi bomi lagche',
  'pete betha',
  'paye betha',
  'komor betha',
  'haat betha',
  'buk betha',
  'joint betha',
  'shorir betha',
  'durbol lagche',
  'khub durbol',
  'khawa ichha nei',
  'pait kharap',
  'loose motion',
  'patla paykhana',
  'kosha paykhana',
  'paykhana te rokto',
  'peshab e jwala',
  'bar bar peshab',
  'peshab kom hocche',
  'peshab e rokto',
  'chulkani',
  'fuskuri',
  'ga e daag',
  'sujon',
  'paye sujon',
  'mukhe sujon',
  'rokto porche',
  'ghum hocche na',
  'chinta hocche',
  'bhoy lagche',
  'current er moto betha',
  'bidyut shock er moto betha',
  'sui fotar moto',
  'jhin jhin korche',
  'obosh lagche',
  'kal theke',
  'aj sokal theke',
  'du din dhore',
  'ek soptaho dhore',
  'onek din dhore',

  // --------------------------------------------------
  // Bengali/Hindi pain words and local variants
  // --------------------------------------------------
  'byatha',
  'betha',
  'dard',
  'jontrona',
  'jantrana',
  'shul',
  'shulano',
  'jwala',
  'jalan',
  'khujli',
  'chulkani',
  'sujan',
  'sujon',
  'kamjori',
  'durbolota',
  'ghabrahat',
  'bechaini',
  'gas',
  'ombol',
  'pait kharap',
  'pet kharab',

  // --------------------------------------------------
  // Red-flag phrases to capture accurately
  // --------------------------------------------------
  'severe chest pain',
  'chest pain with sweating',
  'chest pain with breathlessness',
  'sudden weakness',
  'one side weakness',
  'slurred speech',
  'facial droop',
  'loss of consciousness',
  'seizure',
  'fits',
  'blood vomiting',
  'vomiting blood',
  'blood in stool',
  'black stool',
  'blood in urine',
  'severe abdominal pain',
  'severe headache',
  'worst headache of life',
  'neck stiffness',
  'high fever with confusion',
  'difficulty breathing',
  'oxygen low',
  'pregnancy bleeding',
  'reduced fetal movement',
  'suicidal thoughts',
  'poisoning',
  'snake bite',
  'dog bite',
  'burn injury',
  'road accident',
  'fall from height'
];

module.exports = medicalPhrases;